-- 테스트용 DB 및 데이터

-- test_festival 데이터베이스 구조 내보내기
CREATE DATABASE IF NOT EXISTS `test_festival`;
USE `test_festival`;

-- 테이블 test_festival.fake_festival 구조 내보내기
CREATE TABLE IF NOT EXISTS `fake_festival` (
  `ID` int(11) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `ORIGIN` varchar(100) NOT NULL,
  `CONTENT` varchar(1000) NOT NULL,
  `IMAGE` varchar(50) NOT NULL,
  `STARTDATE` date NOT NULL,
  `ENDDATE` date NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 테이블 데이터 test_festival.fake_festival:~50 rows (대략적) 내보내기
INSERT INTO `fake_festival` (`ID`, `TITLE`, `ORIGIN`, `CONTENT`, `IMAGE`, `STARTDATE`, `ENDDATE`) VALUES
	(1, 'Move Over, Darling', 'https://pagesperso-orange.fr/eleifend/quam/a.json', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'http://dummyimage.com/133x102.png/dddddd/000000', '2024-07-07', '2024-07-13'),
	(2, 'A Thousand Times Goodnight', 'https://google.pl/sollicitudin/vitae/consectetuer/eget/rutrum/at/lorem.jsp', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/152x233.png/ff4444/ffffff', '2024-11-07', '2024-11-13'),
	(3, 'Cloud 9', 'https://sitemeter.com/sed/nisl/nunc/rhoncus.json', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'http://dummyimage.com/140x226.png/cc0000/ffffff', '2024-09-12', '2024-09-15'),
	(4, 'Last Godfather, The', 'http://ustream.tv/pellentesque/eget.aspx', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://dummyimage.com/110x146.png/cc0000/ffffff', '2024-09-06', '2024-09-10'),
	(5, 'Ballad of Nessie, The', 'http://latimes.com/proin/at/turpis/a/pede.jpg', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://dummyimage.com/146x197.png/ff4444/ffffff', '2024-11-28', '2024-11-30'),
	(6, 'Santa Claus: The Movie', 'http://slate.com/libero/non.png', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'http://dummyimage.com/112x159.png/ff4444/ffffff', '2024-08-08', '2024-08-12'),
	(7, 'RFK Must Die: The Assassination of Bobby Kennedy', 'http://ebay.com/donec/diam/neque/vestibulum/eget/vulputate/ut.jsp', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'http://dummyimage.com/111x242.png/cc0000/ffffff', '2024-06-22', '2024-06-25'),
	(8, 'American Soldiers', 'http://ft.com/integer.jsp', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/205x148.png/ff4444/ffffff', '2024-11-19', '2024-11-19'),
	(9, 'Code, The (Mentale, La)', 'http://virginia.edu/morbi/quis/tortor/id/nulla.jpg', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/245x144.png/cc0000/ffffff', '2024-07-30', '2024-07-31'),
	(10, 'Theatre Bizarre, The', 'http://howstuffworks.com/quam/sollicitudin.jpg', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://dummyimage.com/147x173.png/5fa2dd/ffffff', '2024-09-28', '2024-09-28'),
	(11, 'Lisa Picard is Famous (a.k.a. Famous)', 'https://time.com/vivamus/tortor/duis/mattis/egestas/metus/aenean.png', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/140x185.png/ff4444/ffffff', '2024-11-20', '2024-11-22'),
	(12, 'Bay of Angels (La baie des anges)', 'http://bandcamp.com/iaculis.aspx', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/130x203.png/dddddd/000000', '2024-12-20', '2024-12-25'),
	(13, 'Stonewall', 'http://about.me/parturient.jpg', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/104x114.png/cc0000/ffffff', '2024-12-03', '2024-12-04'),
	(14, 'Cinderella II: Dreams Come True', 'https://oakley.com/dapibus/nulla/suscipit/ligula.json', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'http://dummyimage.com/179x208.png/cc0000/ffffff', '2024-06-24', '2024-06-24'),
	(15, 'Corn Is Green, The', 'http://loc.gov/vel/sem.xml', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'http://dummyimage.com/249x229.png/5fa2dd/ffffff', '2024-06-07', '2024-06-13'),
	(16, 'Shopgirl', 'http://columbia.edu/placerat/praesent/blandit.html', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/158x241.png/ff4444/ffffff', '2024-06-06', '2024-06-12'),
	(17, 'Everly', 'https://ocn.ne.jp/nulla/quisque/arcu/libero/rutrum/ac.html', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://dummyimage.com/101x243.png/dddddd/000000', '2024-12-20', '2024-12-20'),
	(18, 'Satan\'s Sword 3: The Final Chapter (Daibosatsu toge: Kanketsu-hen)', 'https://ox.ac.uk/nec/molestie/sed/justo/pellentesque/viverra.jsp', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://dummyimage.com/212x218.png/cc0000/ffffff', '2024-10-24', '2024-10-27'),
	(19, 'Man in Grey, The', 'http://123-reg.co.uk/augue/quam/sollicitudin/vitae/consectetuer.json', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'http://dummyimage.com/144x173.png/cc0000/ffffff', '2024-12-04', '2024-12-09'),
	(20, 'Tunes of Glory', 'http://vimeo.com/nonummy.jpg', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/214x170.png/dddddd/000000', '2024-11-05', '2024-11-06'),
	(21, 'Real McCoy, The', 'https://ezinearticles.com/pede/justo/eu.jsp', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://dummyimage.com/249x192.png/5fa2dd/ffffff', '2024-07-04', '2024-07-10'),
	(22, 'Ladrón que roba a ladrón', 'http://macromedia.com/fusce/posuere/felis/sed.js', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/162x222.png/ff4444/ffffff', '2024-09-18', '2024-09-20'),
	(23, 'Murder Party', 'https://canalblog.com/nec/nisi/volutpat/eleifend/donec.xml', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/108x219.png/dddddd/000000', '2024-07-27', '2024-07-29'),
	(24, 'House of Women', 'http://issuu.com/odio/consequat/varius/integer/ac/leo.html', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/238x117.png/5fa2dd/ffffff', '2024-06-21', '2024-06-25'),
	(25, 'Ghost in the Shell Arise - Border 1: Ghost Pain', 'http://people.com.cn/commodo/placerat.html', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'http://dummyimage.com/196x110.png/ff4444/ffffff', '2024-06-07', '2024-06-12'),
	(26, 'Sambizanga', 'https://xinhuanet.com/elementum.json', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/156x153.png/ff4444/ffffff', '2024-12-14', '2024-12-17'),
	(27, 'Bullfighter, The (Matador)', 'https://unesco.org/tincidunt/eget/tempus.aspx', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/114x193.png/5fa2dd/ffffff', '2024-12-08', '2024-12-08'),
	(28, 'Sassy Pants', 'http://rediff.com/varius/integer/ac/leo/pellentesque/ultrices/mattis.js', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/203x113.png/ff4444/ffffff', '2024-11-19', '2024-11-20'),
	(29, 'Tulsa', 'http://economist.com/eros.aspx', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'http://dummyimage.com/105x132.png/ff4444/ffffff', '2024-12-31', '2025-01-06'),
	(30, 'Hot Fuzz', 'http://acquirethisname.com/justo/morbi/ut/odio/cras/mi/pede.xml', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://dummyimage.com/156x231.png/cc0000/ffffff', '2024-06-06', '2024-06-13'),
	(31, 'A Cry in the Wild', 'https://tuttocitta.it/et/tempus/semper/est/quam/pharetra.js', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'http://dummyimage.com/170x244.png/cc0000/ffffff', '2024-08-12', '2024-08-18'),
	(32, 'City Zero', 'http://flickr.com/eget/rutrum.aspx', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/112x221.png/5fa2dd/ffffff', '2024-09-21', '2024-09-28'),
	(33, 'Fish Child, The (El niño pez)', 'https://de.vu/fermentum/donec/ut/mauris/eget/massa/tempor.xml', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/204x134.png/dddddd/000000', '2024-08-21', '2024-08-28'),
	(34, 'Thousand Clouds of Peace, A (Mil nubes de paz cercan el cielo, amor, jamás acabarás de ser amor)', 'https://ibm.com/nulla/sed/vel.jsp', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'http://dummyimage.com/120x246.png/dddddd/000000', '2024-11-17', '2024-11-22'),
	(35, 'Chemical Brothers: Don\'t Think, The', 'https://reuters.com/ut/rhoncus/aliquet/pulvinar/sed/nisl/nunc.json', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/125x144.png/cc0000/ffffff', '2024-12-26', '2024-12-31'),
	(36, 'Vampire in Venice (Nosferatu a Venezia) (Nosferatu in Venice)', 'https://gmpg.org/montes/nascetur/ridiculus/mus/vivamus/vestibulum/sagittis.xml', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://dummyimage.com/243x102.png/cc0000/ffffff', '2024-11-19', '2024-11-21'),
	(37, 'At Berkeley', 'http://shop-pro.jp/dignissim.jsp', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'http://dummyimage.com/142x158.png/cc0000/ffffff', '2024-12-30', '2025-01-02'),
	(38, 'Abbott and Costello Go to Mars', 'https://aol.com/metus/aenean/fermentum/donec.json', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/175x139.png/ff4444/ffffff', '2024-12-01', '2024-12-05'),
	(39, 'Sentinel, The', 'https://nasa.gov/id.jpg', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://dummyimage.com/141x104.png/5fa2dd/ffffff', '2024-08-09', '2024-08-13'),
	(40, 'Nemesis 3: Time Lapse', 'https://parallels.com/sed/justo/pellentesque/viverra/pede.jsp', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/150x153.png/5fa2dd/ffffff', '2024-11-09', '2024-11-10'),
	(41, 'Wallace & Gromit in The Curse of the Were-Rabbit', 'http://prlog.org/sit/amet/diam.png', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.', 'http://dummyimage.com/131x183.png/dddddd/000000', '2024-06-21', '2024-06-24'),
	(42, 'Seven Years in Tibet', 'https://unblog.fr/donec/ut/dolor.xml', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/133x141.png/5fa2dd/ffffff', '2024-09-02', '2024-09-02'),
	(43, 'Bhaji on the Beach', 'http://ca.gov/ligula/suspendisse/ornare.aspx', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/110x175.png/ff4444/ffffff', '2024-10-03', '2024-10-09'),
	(44, 'Hugo Pool', 'https://bloomberg.com/nisi/volutpat/eleifend/donec.aspx', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://dummyimage.com/196x150.png/dddddd/000000', '2024-07-20', '2024-07-22'),
	(45, 'Lupin III: First Contact (Rupan Sansei: Faasuto Kontakuto)', 'https://buzzfeed.com/vestibulum/vestibulum.html', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/164x147.png/5fa2dd/ffffff', '2024-11-29', '2024-12-04'),
	(46, 'Revenge of the Pink Panther', 'https://ihg.com/fusce.xml', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'http://dummyimage.com/231x115.png/dddddd/000000', '2024-08-01', '2024-08-02'),
	(47, 'The Fat Spy', 'https://stanford.edu/suspendisse.xml', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.', 'http://dummyimage.com/200x115.png/dddddd/000000', '2024-11-25', '2024-11-27'),
	(48, 'Let the Fire Burn', 'http://forbes.com/risus/semper/porta.png', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://dummyimage.com/172x101.png/5fa2dd/ffffff', '2024-10-03', '2024-10-06'),
	(49, 'That Night in Varennes (Nuit de Varennes, La)', 'http://squarespace.com/nam.xml', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'http://dummyimage.com/203x237.png/dddddd/000000', '2024-11-06', '2024-11-13'),
	(50, 'Don Quixote', 'http://so-net.ne.jp/amet/nunc.jpg', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://dummyimage.com/216x224.png/ff4444/ffffff', '2024-09-08', '2024-09-10');
